language: java
#install: mvn install:install-file -Dfile=libs/zap-2.4.3.jar -DgroupId=org.zaproxy -DartifactId=zaproxy -Dversion=2.4.3 -Dpackaging=jar
jdk:
  - openjdk8
  - openjdk9
  - openjdk10

services:
  - xvfb
